### ISSUE TITLE
Perplexity Calculation

### ISSUE THREAD

**Issue by LucFumag** [SocialComplexityLab/life2vec#8]
Hello,

I noticed that in the code, perplexity is calculated as the square root of the loss. As far as I know, it can be calculated using the exponential transformation of the loss.

Can you explain why the metrics are calculated this way and provide any source materials that explain this approach?

Thank you in advance for your attention and answers.

**Comment by carlomarxdk** [comment]
Hey there, 
Thanks for the question!

We (initially) used the exponential transform of the loss (to record `perplexity`), but when we had to perform the hyperparameter search, we switched to the square root. Since our hyperparameter choice depends on two losses (one from the MLM and one from the SOP tasks), we wanted them to be on the same order of magnitude (and the square root transform seemed to do the trick).

Subsequently, I **forgot to rename the metric** we are tracking (and kept it as `perplexity`). 
**You are 100% correct that `perplexity` is the exponential transformation of the cross-entry loss.** 

Sorry for the confusion.

**Comment by LucFumag** [comment]
All clear, thank you very much!

**Comment by LucFumag** [comment]
All clear, thank you very much!

**Comment by tanzir5** [comment]
The perplexity reported in the appendix of the paper  -- Is that the square root of the loss or actual perplexity?

**Comment by carlomarxdk** [comment]
> The perplexity reported in the appendix of the paper -- Is that the square root of the loss or actual perplexity?

In the Appendix, it is a square root of the two losses (Masked Language Modeling and Sequence Order prediction).
In the Thesis, Fig. 16 displays an actual perplexity for the MLM loss: [link to the thesis](https://orbit.dtu.dk/en/publications/life-trajectories-as-symbolic-language).

**Comment by tanzir5** [comment]
Thank you!
